/**
 * Ftl.Backoffice.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactItem } from './contactItem';


export interface ContactEventItem { 
    createdBy?: string | null;
    created?: string;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    id?: string;
    contact?: ContactItem;
    contactId?: number;
    eventType?: string | null;
    isJson?: boolean | null;
    data?: string | null;
    metaData?: string | null;
}

