/**
 * Ftl.Backoffice.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactEventItem } from './contactEventItem';


export interface ContactItem { 
    createdBy?: string | null;
    created?: string;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    id?: number;
    name?: string | null;
    email?: string | null;
    contactEvents?: Array<ContactEventItem> | null;
}

