/**
 * Ftl.Backoffice.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItem { 
    createdBy?: string | null;
    created?: string;
    lastModifiedBy?: string | null;
    lastModified?: string | null;
    id?: number;
    contactId?: number;
    contactEmail?: string | null;
    executionId?: string | null;
    status?: string | null;
    netPrice?: number | null;
}

